apiVersion: apps/v1
kind: Deployment
metadata:
  name: skybank-backend
spec:
  replicas: 2  # This is the "Magic". K8s will ensure 2 copies are always running.
  selector:
    matchLabels:
      app: skybank-backend
  template:
    metadata:
      labels:
        app: skybank-backend
    spec:
      containers:
      - name: backend
        image: smfprecise/skybank-backend:v1 # K8s pulls this from the registry
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://skyadmin:skypassword@skybank-db:5432/skybank_db"
---
apiVersion: v1
kind: Service
metadata:
  name: skybank-backend
spec:
  selector:
    app: skybank-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
